import "@/app/globals.css"
import Header from "@/components/Header"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <header><Header /></header>
        <main>{children}</main>
      </body>
    </html>
  )
}
